#!/usr/bin/env python3
"""Generate include/sidekick_device_config.h from .env files and environment."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.is_file():
        return data

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        data[key] = value
    return data


def c_string(value: str, max_len: int | None = None) -> str:
    if max_len is not None and len(value) > max_len:
        raise ValueError(f"value too long ({len(value)} > {max_len}): {value!r}")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def merge_config(app_root: Path) -> dict[str, str]:
    defaults = {
        "SIDEKICK_BACKEND_HOST": "",
        "SIDEKICK_BACKEND_PORT": "8787",
        "SIDEKICK_BACKEND_SESSION_ID": "sidekick",
        "SIDEKICK_WIFI_SSID": "",
        "SIDEKICK_WIFI_PSWD": "",
    }

    merged = dict(defaults)
    for name in (".env.example", ".env", ".env.local"):
        merged.update(parse_env_file(app_root / name))

    for key in defaults:
        env_val = os.environ.get(key)
        if env_val is not None:
            merged[key] = env_val

    return merged


def render_header(cfg: dict[str, str]) -> str:
    host = cfg["SIDEKICK_BACKEND_HOST"]
    port = int(cfg.get("SIDEKICK_BACKEND_PORT", "8787") or "8787")
    session = cfg["SIDEKICK_BACKEND_SESSION_ID"]
    ssid = cfg["SIDEKICK_WIFI_SSID"]
    pswd = cfg["SIDEKICK_WIFI_PSWD"]

    return f"""/* Auto-generated by scripts/gen_sidekick_device_config.py — do not edit. */
#ifndef SIDEKICK_DEVICE_CONFIG_H
#define SIDEKICK_DEVICE_CONFIG_H

#define SIDEKICK_BACKEND_HOST       {c_string(host)}
#define SIDEKICK_BACKEND_PORT       {port}
#define SIDEKICK_BACKEND_SESSION_ID {c_string(session, 64)}
#define SIDEKICK_BACKEND_TIMEOUT_MS (120 * 1000)

#define SIDEKICK_WIFI_SSID {c_string(ssid, 32)}
#define SIDEKICK_WIFI_PSWD {c_string(pswd, 64)}

#endif /* SIDEKICK_DEVICE_CONFIG_H */
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--app-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to apps/sidekick",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output header path (default: <app-root>/include/sidekick_device_config.h)",
    )
    args = parser.parse_args()

    app_root = args.app_root.resolve()
    output = args.output or (app_root / "include" / "sidekick_device_config.h")

    try:
        cfg = merge_config(app_root)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render_header(cfg), encoding="utf-8")
    except (ValueError, OSError) as exc:
        print(f"gen_sidekick_device_config: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {output}")
    if cfg["SIDEKICK_BACKEND_HOST"]:
        print(f"  backend={cfg['SIDEKICK_BACKEND_HOST']}:{cfg['SIDEKICK_BACKEND_PORT']}")
    if cfg["SIDEKICK_WIFI_SSID"]:
        print(f"  wifi ssid={cfg['SIDEKICK_WIFI_SSID']!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
