package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
)

func (s *server) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"ok":       true,
		"provider": s.cfg.Provider,
		"model":    s.cfg.analysisModel(),
		"context":  s.cfg.ContextFrames,
		"tts":      s.cfg.TTS.Provider,
	})
}

func (s *server) handleFrame(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	image, _, err := s.readImage(r)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: err.Error()})
		return
	}
	defer image.Close()

	imageBytes, err := io.ReadAll(image)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "failed to read image body"})
		return
	}
	if len(imageBytes) == 0 {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "empty image body"})
		return
	}
	receivedBytes := len(imageBytes)
	if rotated, ok := rotateJPEG180(imageBytes); ok {
		imageBytes = rotated
	}

	sessionID := normalizeSessionID(r.URL.Query().Get("session"))
	mode := normalizeMode(r.URL.Query().Get("mode"))
	transcript := s.latestTranscript(sessionID)
	s.persistCapture(sessionID, mode, imageBytes)
	if mode == "summary" {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "summary is generated by POST /sidekick/session/end"})
		return
	}
	priorFrames := s.sessionFrames(sessionID)

	message, shouldRespond, provider, err := s.analyze(r.Context(), mode, imageBytes, priorFrames, transcript, false)
	if err != nil {
		logError("analysis failed", "error", err)
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}
	s.recordFrame(sessionID, frameContext{
		Image:         append([]byte(nil), imageBytes...),
		Mode:          mode,
		Message:       message,
		Transcript:    transcript,
		ShouldRespond: shouldRespond,
		ObservedAt:    time.Now(),
	})
	if transcript != "" {
		s.clearLatestTranscript(sessionID, transcript)
	}

	if s.cfg.Verbose {
		logInfo("frame result", "session", sessionID, "provider", provider, "mode", mode, "should_respond", shouldRespond, "message", message)
	}

	s.maybeGenerateTTS(r.Context(), shouldRespond, message)

	writeJSON(w, http.StatusOK, sidekickResponse{
		Mode:          mode,
		SessionID:     sessionID,
		Provider:      provider,
		Message:       message,
		ShouldRespond: shouldRespond,
		ReceivedBytes: receivedBytes,
		LatencyMS:     time.Since(start).Milliseconds(),
		Transcript:    transcript,
	})
}

func rotateJPEG180(data []byte) ([]byte, bool) {
	source, err := jpeg.Decode(bytes.NewReader(data))
	if err != nil {
		return data, false
	}

	bounds := source.Bounds()
	rotated := image.NewRGBA(image.Rect(0, 0, bounds.Dx(), bounds.Dy()))
	for y := 0; y < bounds.Dy(); y++ {
		for x := 0; x < bounds.Dx(); x++ {
			rotated.Set(bounds.Dx()-1-x, bounds.Dy()-1-y, source.At(bounds.Min.X+x, bounds.Min.Y+y))
		}
	}

	var output bytes.Buffer
	if err := jpeg.Encode(&output, rotated, &jpeg.Options{Quality: 95}); err != nil {
		return data, false
	}

	return output.Bytes(), true
}

func (s *server) handleAudio(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, s.cfg.STT.MaxAudioBytes)
	audio, err := io.ReadAll(r.Body)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "failed to read audio body"})
		return
	}
	if len(audio) == 0 {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "empty audio body"})
		return
	}

	sampleRate := queryInt(r, "sample_rate", 16000)
	channels := queryInt(r, "channels", 1)
	bits := queryInt(r, "bits", 16)
	sessionID := normalizeSessionID(r.URL.Query().Get("session"))

	transcript, provider, err := s.transcribeAudio(r.Context(), audio, sampleRate, channels, bits)
	if err != nil {
		logError("transcription failed", "error", err)
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}
	pendingTranscript := s.appendTranscript(sessionID, transcript)
	if s.cfg.Verbose {
		logInfo("audio transcript", "session", sessionID, "provider", provider, "bytes", len(audio), "transcript", transcript, "pending", pendingTranscript)
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"session_id":     sessionID,
		"provider":       provider,
		"transcript":     transcript,
		"received_bytes": len(audio),
		"latency_ms":     time.Since(start).Milliseconds(),
	})
}

func (s *server) handleSessionEnd(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	sessionID := normalizeSessionID(r.URL.Query().Get("session"))
	frames := s.sessionFrames(sessionID)
	if len(frames) == 0 {
		writeJSON(w, http.StatusNotFound, errorResponse{Error: "session has no captured frames"})
		return
	}

	message, shouldRespond, provider, err := s.analyze(r.Context(), "summary", nil, frames, s.latestTranscript(sessionID), true)
	if err != nil {
		logError("summary failed", "error", err)
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}
	s.clearSession(sessionID)

	if s.cfg.Verbose {
		logInfo("summary result", "session", sessionID, "provider", provider, "should_respond", shouldRespond, "message", message)
	}

	s.maybeGenerateTTS(r.Context(), shouldRespond, message)

	writeJSON(w, http.StatusOK, sidekickResponse{
		Mode:          "summary",
		SessionID:     sessionID,
		Provider:      provider,
		Message:       message,
		ShouldRespond: shouldRespond,
		LatencyMS:     time.Since(start).Milliseconds(),
	})
}

func (s *server) handleTTS(w http.ResponseWriter, r *http.Request) {
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	var req ttsRequest
	r.Body = http.MaxBytesReader(w, r.Body, int64(s.cfg.TTS.MaxChars*4+1024))
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "invalid JSON body"})
		return
	}

	text := strings.TrimSpace(req.Text)
	if text == "" {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "text is required"})
		return
	}
	if len([]rune(text)) > s.cfg.TTS.MaxChars {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: fmt.Sprintf("text exceeds %d characters", s.cfg.TTS.MaxChars)})
		return
	}

	provider := strings.ToLower(strings.TrimSpace(req.Provider))
	if provider == "" {
		provider = s.cfg.TTS.Provider
	}

	key := normalizeTextKey(text)
	var entry ttsCacheEntry
	var found bool

	if entry, found = s.getCachedTTS(key); !found {
		// Try prefix match on cached keys (in case of client truncation)
		s.mu.Lock()
		for cachedKey, cachedEntry := range s.ttsCache {
			if len(key) >= 10 && strings.HasPrefix(cachedKey, key) {
				entry = cachedEntry
				found = true
				if s.cfg.Verbose {
					logInfo("TTS cache prefix match hit", "requested", key, "matched", cachedKey)
				}
				break
			}
		}
		s.mu.Unlock()
	}

	if found {
		if s.cfg.Verbose {
			logInfo("TTS cache hit", "key", key, "bytes", len(entry.Audio))
		}
		w.Header().Set("Content-Type", entry.ContentType)
		w.Header().Set("Content-Length", strconv.Itoa(len(entry.Audio)))
		w.Header().Set("X-Sidekick-TTS-Provider", provider+"-cached")
		w.Header().Set("X-Sidekick-Audio-Format", entry.Format)
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write(entry.Audio); err != nil {
			logError("failed to write TTS audio", "error", err)
		}
		return
	}

	audio, contentType, format, err := s.synthesizeSpeech(r.Context(), provider, req)
	if err != nil {
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}

	s.cacheTTS(key, audio, contentType, format, text)

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Length", strconv.Itoa(len(audio)))
	w.Header().Set("X-Sidekick-TTS-Provider", provider)
	w.Header().Set("X-Sidekick-Audio-Format", format)
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write(audio); err != nil {
		logError("failed to write TTS audio", "error", err)
	}
}
