package main

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	defaultPort          = "8787"
	defaultProvider      = "ollama"
	defaultOllamaModel   = "gemma4:26b"
	defaultOllamaChatURL = "http://localhost:11434/api/chat"
	defaultMaxImageBytes = 4 * 1024 * 1024
	defaultContextFrames = 3
	defaultSessionID     = "default"
)

type config struct {
	Port             string
	Provider         string
	OllamaModel      string
	OllamaChatURL    string
	MaxImageBytes    int64
	SharedSecret     string
	RequestTimeout   time.Duration
	MaxOutputTokens  int
	ContextFrames    int
	AllowMultipart   bool
	DefaultImageMIME string
}

type server struct {
	cfg      config
	client   *http.Client
	mu       sync.Mutex
	sessions map[string]*sessionState
}

type sessionState struct {
	Frames []frameContext
}

type frameContext struct {
	Image         []byte
	Mode          string
	Message       string
	ShouldRespond bool
	ObservedAt    time.Time
}

type sidekickResponse struct {
	Mode          string `json:"mode"`
	SessionID     string `json:"session_id,omitempty"`
	Provider      string `json:"provider"`
	Message       string `json:"message"`
	ShouldRespond bool   `json:"should_respond"`
	ReceivedBytes int    `json:"received_bytes"`
	LatencyMS     int64  `json:"latency_ms"`
}

type errorResponse struct {
	Error string `json:"error"`
}

func main() {
	cfg := loadConfig()
	srv := newServer(cfg)

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", srv.handleHealth)
	mux.HandleFunc("POST /sidekick/frame", srv.handleFrame)
	mux.HandleFunc("POST /sidekick/session/end", srv.handleSessionEnd)

	addr := ":" + cfg.Port
	log.Printf("SideKick backend listening on %s provider=%s model=%s", addr, cfg.Provider, cfg.OllamaModel)
	log.Fatal(http.ListenAndServe(addr, logRequests(mux)))
}

func loadConfig() config {
	provider := getenv("SIDEKICK_AI_PROVIDER", defaultProvider)

	return config{
		Port:             getenv("PORT", defaultPort),
		Provider:         strings.ToLower(provider),
		OllamaModel:      getenv("OLLAMA_MODEL", defaultOllamaModel),
		OllamaChatURL:    getenv("OLLAMA_CHAT_URL", defaultOllamaChatURL),
		MaxImageBytes:    getenvInt64("SIDEKICK_MAX_IMAGE_BYTES", defaultMaxImageBytes),
		SharedSecret:     os.Getenv("SIDEKICK_SHARED_SECRET"),
		RequestTimeout:   time.Duration(getenvInt64("SIDEKICK_TIMEOUT_SECONDS", 120)) * time.Second,
		MaxOutputTokens:  int(getenvInt64("SIDEKICK_MAX_OUTPUT_TOKENS", 240)),
		ContextFrames:    int(getenvInt64("SIDEKICK_CONTEXT_FRAMES", defaultContextFrames)),
		AllowMultipart:   getenv("SIDEKICK_ALLOW_MULTIPART", "1") != "0",
		DefaultImageMIME: getenv("SIDEKICK_IMAGE_MIME", "image/jpeg"),
	}
}

func newServer(cfg config) *server {
	return &server{
		cfg: cfg,
		client: &http.Client{
			Timeout: cfg.RequestTimeout,
		},
		sessions: make(map[string]*sessionState),
	}
}

func (s *server) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"ok":       true,
		"provider": s.cfg.Provider,
		"model":    s.cfg.OllamaModel,
		"context":  s.cfg.ContextFrames,
	})
}

func (s *server) handleFrame(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	image, _, err := s.readImage(r)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: err.Error()})
		return
	}
	defer image.Close()

	imageBytes, err := io.ReadAll(image)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "failed to read image body"})
		return
	}
	if len(imageBytes) == 0 {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "empty image body"})
		return
	}

	mode := normalizeMode(r.URL.Query().Get("mode"))
	if mode == "summary" {
		writeJSON(w, http.StatusBadRequest, errorResponse{Error: "summary is generated by POST /sidekick/session/end"})
		return
	}
	sessionID := normalizeSessionID(r.URL.Query().Get("session"))
	priorFrames := s.sessionFrames(sessionID)

	message, shouldRespond, provider, err := s.analyze(r.Context(), mode, imageBytes, priorFrames, false)
	if err != nil {
		log.Printf("analysis failed: %v", err)
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}
	s.recordFrame(sessionID, frameContext{
		Image:         append([]byte(nil), imageBytes...),
		Mode:          mode,
		Message:       message,
		ShouldRespond: shouldRespond,
		ObservedAt:    time.Now(),
	})

	writeJSON(w, http.StatusOK, sidekickResponse{
		Mode:          mode,
		SessionID:     sessionID,
		Provider:      provider,
		Message:       message,
		ShouldRespond: shouldRespond,
		ReceivedBytes: len(imageBytes),
		LatencyMS:     time.Since(start).Milliseconds(),
	})
}

func (s *server) handleSessionEnd(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if !s.authorized(r) {
		writeJSON(w, http.StatusUnauthorized, errorResponse{Error: "unauthorized"})
		return
	}

	sessionID := normalizeSessionID(r.URL.Query().Get("session"))
	frames := s.sessionFrames(sessionID)
	if len(frames) == 0 {
		writeJSON(w, http.StatusNotFound, errorResponse{Error: "session has no captured frames"})
		return
	}

	message, shouldRespond, provider, err := s.analyze(r.Context(), "summary", nil, frames, true)
	if err != nil {
		log.Printf("summary failed: %v", err)
		writeJSON(w, http.StatusBadGateway, errorResponse{Error: err.Error()})
		return
	}
	s.clearSession(sessionID)

	writeJSON(w, http.StatusOK, sidekickResponse{
		Mode:          "summary",
		SessionID:     sessionID,
		Provider:      provider,
		Message:       message,
		ShouldRespond: shouldRespond,
		LatencyMS:     time.Since(start).Milliseconds(),
	})
}

func (s *server) authorized(r *http.Request) bool {
	if s.cfg.SharedSecret == "" {
		return true
	}

	auth := r.Header.Get("Authorization")
	if strings.HasPrefix(auth, "Bearer ") && strings.TrimPrefix(auth, "Bearer ") == s.cfg.SharedSecret {
		return true
	}

	return r.Header.Get("X-Sidekick-Token") == s.cfg.SharedSecret
}

func (s *server) readImage(r *http.Request) (io.ReadCloser, string, error) {
	r.Body = http.MaxBytesReader(nil, r.Body, s.cfg.MaxImageBytes)

	contentType := r.Header.Get("Content-Type")
	if s.cfg.AllowMultipart && strings.HasPrefix(contentType, "multipart/form-data") {
		file, header, err := r.FormFile("file")
		if err != nil {
			return nil, "", errors.New("multipart request must include file field named file")
		}
		mimeType := header.Header.Get("Content-Type")
		if mimeType == "" {
			mimeType = s.cfg.DefaultImageMIME
		}
		return file, mimeType, nil
	}

	mimeType := contentType
	if semicolon := strings.IndexByte(mimeType, ';'); semicolon >= 0 {
		mimeType = mimeType[:semicolon]
	}
	mimeType = strings.TrimSpace(mimeType)
	if mimeType == "" || mimeType == "application/octet-stream" {
		mimeType = s.cfg.DefaultImageMIME
	}

	return r.Body, mimeType, nil
}

func (s *server) analyze(ctx context.Context, mode string, image []byte, priorFrames []frameContext, summary bool) (string, bool, string, error) {
	switch s.cfg.Provider {
	case "fake", "mock", "":
		return fakeMessage(mode, summary), true, "fake", nil
	case "ollama":
		message, err := s.callOllama(ctx, mode, image, priorFrames, summary)
		if err != nil {
			return "", false, "ollama", err
		}
		message, shouldRespond := parseModelDecision(message)
		if summary && !shouldRespond {
			return "Session ended. Review the last visible step and choose the next small move.", true, "ollama", nil
		}
		return message, shouldRespond, "ollama", nil
	default:
		return "", false, s.cfg.Provider, fmt.Errorf("unsupported SIDEKICK_AI_PROVIDER %q", s.cfg.Provider)
	}
}

func (s *server) callOllama(ctx context.Context, mode string, image []byte, priorFrames []frameContext, summary bool) (string, error) {
	messages := []ollamaMessage{{
		Role:    "system",
		Content: tutorSystemPrompt(mode, summary),
	}}

	for idx, frame := range priorFrames {
		content := fmt.Sprintf("Previous frame %d of %d. Mode=%s. Time=%s. Previous tutor message=%q. Compare this with later frames.",
			idx+1, len(priorFrames), frame.Mode, frame.ObservedAt.Format(time.RFC3339), frame.Message)
		messages = append(messages, ollamaMessage{
			Role:    "user",
			Content: content,
			Images:  []string{base64.StdEncoding.EncodeToString(frame.Image)},
		})
	}

	if image != nil {
		messages = append(messages, ollamaMessage{
			Role:    "user",
			Content: "Current frame. Compare it with the previous frames, infer progress or lack of motion, and respond with only the tutor message or NO_ACTION.",
			Images:  []string{base64.StdEncoding.EncodeToString(image)},
		})
	} else {
		messages = append(messages, ollamaMessage{
			Role:    "user",
			Content: "The session has ended. Use the provided frames in order to summarize progress and the best next step.",
		})
	}

	payload := ollamaChatRequest{
		Model:    s.cfg.OllamaModel,
		Stream:   false,
		Think:    false,
		Messages: messages,
		Options: ollamaOptions{
			Temperature: 0.2,
			NumPredict:  s.cfg.MaxOutputTokens,
		},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, s.cfg.OllamaChatURL, bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := s.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 2*1024*1024))
	if err != nil {
		return "", err
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("Ollama returned HTTP %d: %s", resp.StatusCode, string(respBody))
	}

	var parsed ollamaChatResponse
	if err := json.Unmarshal(respBody, &parsed); err != nil {
		return "", err
	}
	if parsed.Error != "" {
		return "", errors.New(parsed.Error)
	}

	text := cleanModelText(parsed.Message.Content)
	if text == "" {
		return "", errors.New("Ollama response did not include message content")
	}
	return text, nil
}

type ollamaChatRequest struct {
	Model    string          `json:"model"`
	Messages []ollamaMessage `json:"messages"`
	Stream   bool            `json:"stream"`
	Think    bool            `json:"think"`
	Options  ollamaOptions   `json:"options,omitempty"`
}

type ollamaMessage struct {
	Role     string   `json:"role"`
	Content  string   `json:"content"`
	Images   []string `json:"images,omitempty"`
	Thinking string   `json:"thinking,omitempty"`
}

type ollamaOptions struct {
	Temperature float64 `json:"temperature,omitempty"`
	NumPredict  int     `json:"num_predict,omitempty"`
}

type ollamaChatResponse struct {
	Message ollamaMessage `json:"message"`
	Error   string        `json:"error,omitempty"`
}

func normalizeMode(mode string) string {
	switch strings.ToLower(strings.TrimSpace(mode)) {
	case "active", "hint", "summary":
		return strings.ToLower(strings.TrimSpace(mode))
	default:
		return "hint"
	}
}

func tutorSystemPrompt(mode string, summary bool) string {
	base := "You are SideKick, a visual AI tutor watching ordered snapshots from a student's desk. Compare the current frame with prior frames to infer motion, progress, pauses, and possible wrong direction. Respond with one short message suitable for a tiny device screen. Use at most 25 words. Do not explain your reasoning. Do not mention camera frames or images."
	if summary {
		return base + " The session has ended. Summarize what the student worked on, visible progress, and one concrete next step. Never return NO_ACTION."
	}
	switch mode {
	case "active":
		return base + " Active mode: intervene when the student appears stuck, has stopped changing the work, or is writing something incorrect. Otherwise return exactly NO_ACTION."
	default:
		return base + " Hint mode: stay quiet unless the student is stuck or going the wrong direction. If no hint is necessary, return exactly NO_ACTION."
	}
}

func fakeMessage(mode string, summary bool) string {
	if summary {
		return "You made visible progress. Review the last step and decide the next small move."
	}
	switch mode {
	case "active":
		return "What is the first thing you can label or simplify here?"
	default:
		return "Try identifying the main equation or diagram first."
	}
}

func parseModelDecision(text string) (string, bool) {
	text = cleanModelText(text)
	decision := strings.Trim(strings.TrimSpace(text), "\"'` .\n\t")
	if strings.EqualFold(decision, "NO_ACTION") {
		return "", false
	}
	return text, strings.TrimSpace(text) != ""
}

func cleanModelText(text string) string {
	text = strings.TrimSpace(text)
	for {
		start := strings.Index(text, "<|channel>thought")
		if start < 0 {
			break
		}
		end := strings.Index(text[start:], "<channel|>")
		if end < 0 {
			text = strings.TrimSpace(text[:start])
			break
		}
		text = text[:start] + text[start+end+len("<channel|>"):]
		text = strings.TrimSpace(text)
	}
	text = strings.ReplaceAll(text, "<|channel>final<|message>", "")
	text = strings.ReplaceAll(text, "<|message>", "")
	return strings.TrimSpace(text)
}

func normalizeSessionID(sessionID string) string {
	sessionID = strings.TrimSpace(sessionID)
	if sessionID == "" {
		return defaultSessionID
	}
	return sessionID
}

func (s *server) sessionFrames(sessionID string) []frameContext {
	s.mu.Lock()
	defer s.mu.Unlock()

	state := s.sessions[sessionID]
	if state == nil || len(state.Frames) == 0 {
		return nil
	}

	frames := make([]frameContext, len(state.Frames))
	for idx, frame := range state.Frames {
		frames[idx] = frame
		frames[idx].Image = append([]byte(nil), frame.Image...)
	}
	return frames
}

func (s *server) recordFrame(sessionID string, frame frameContext) {
	s.mu.Lock()
	defer s.mu.Unlock()

	state := s.sessions[sessionID]
	if state == nil {
		state = &sessionState{}
		s.sessions[sessionID] = state
	}

	state.Frames = append(state.Frames, frame)
	maxFrames := s.cfg.ContextFrames
	if maxFrames <= 0 {
		maxFrames = defaultContextFrames
	}
	if len(state.Frames) > maxFrames {
		state.Frames = append([]frameContext(nil), state.Frames[len(state.Frames)-maxFrames:]...)
	}
}

func (s *server) clearSession(sessionID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.sessions, sessionID)
}

func writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(value); err != nil {
		log.Printf("failed to write JSON response: %v", err)
	}
}

func logRequests(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		log.Printf("%s %s %s", r.Method, r.URL.Path, time.Since(start).Round(time.Millisecond))
	})
}

func getenv(name string, fallback string) string {
	value := os.Getenv(name)
	if value == "" {
		return fallback
	}
	return value
}

func getenvInt64(name string, fallback int64) int64 {
	value := os.Getenv(name)
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseInt(value, 10, 64)
	if err != nil || parsed <= 0 {
		return fallback
	}
	return parsed
}
