#ifndef SIDEKICK_CONFIG_H
#define SIDEKICK_CONFIG_H

#define SIDEKICK_APP_NAME "sidekick"

#define SIDEKICK_CAMERA_WIDTH  480
#define SIDEKICK_CAMERA_HEIGHT 480
#define SIDEKICK_CAMERA_FPS    20

#define SIDEKICK_UI_POLL_MS                50
#define SIDEKICK_TUTOR_TICK_MS             1000
#define SIDEKICK_FRAME_UPLOAD_INTERVAL_SEC 5

#define SIDEKICK_DEFAULT_TUTOR_MODE    SIDEKICK_TUTOR_MODE_HINT
#define SIDEKICK_ENABLE_CAMERA_PREVIEW 0
#define SIDEKICK_ENABLE_STARTUP_CHIME  1

#define SIDEKICK_BACKEND_HOST       ""
#define SIDEKICK_BACKEND_PORT       8787
#define SIDEKICK_BACKEND_SESSION_ID "sidekick"
#define SIDEKICK_BACKEND_TIMEOUT_MS (120 * 1000)

#define SIDEKICK_WIFI_SSID ""
#define SIDEKICK_WIFI_PSWD ""

#endif /* SIDEKICK_CONFIG_H */
