#ifndef SIDEKICK_CONFIG_H
#define SIDEKICK_CONFIG_H

#define SIDEKICK_APP_NAME "sidekick"

#define SIDEKICK_CAMERA_WIDTH  480
#define SIDEKICK_CAMERA_HEIGHT 480
#define SIDEKICK_CAMERA_FPS    20

#define SIDEKICK_TUTOR_TICK_MS 1000

#define SIDEKICK_DEFAULT_TUTOR_MODE SIDEKICK_TUTOR_MODE_HINT

#endif /* SIDEKICK_CONFIG_H */
